### ISSUE TITLE
Gluu 4.1 QA - Null error after OTP QR code screen times out

### ISSUE THREAD

**Issue by sahilIT2020** [GluuFederation/oxAuth#1225]
## Describe the issue
Null error after OTP QR code screen times out

## Steps To Reproduce
1. Enable OTP custom script and set in oxTrust acr default authentication
2. Login to oxtrust UI, and wait until QR screen times out, without registering with OTP device

## Expected behavior
It should give a friendly error message or allow user to retry registration

## Actual behavior
A clear and concise description of what happen.
OOPS error 

##Environment detail

OS: CentOS 7.4
Gluu version(If applicable):4.1 with hybrid (couchbase and wrends)

**Comment by yurem** [comment]
I agree that the error message not explains details. it should show that session timeout. I offer to move this to 4.2 because updates can cause other issues in 4.1 now.

Also oxAuth can't cover re-authenticate flow because even AuthZ can be expired. As result after successful authentication RP can refuse issues code/token. For such case in oxAuth there is property: `errorHandlingMethod: remote`. In this case after login failure (for example session timeout) oxAuth sends user to RP with error response. RP should handle it and re-initiate login flow.

**Comment by yurem** [comment]
Here is how oxTrust handle it:
![image](https://user-images.githubusercontent.com/6104200/71746703-ae1b4080-2e7e-11ea-83a3-6216c5fb835c.png)

**Comment by yurem** [comment]
You can press return `Button` to force relogin

**Comment by yurem** [comment]
It should be fixed in 4.1.1

**Comment by maduvena** [comment]
When QR code times out, we will refresh (reload) QR code

**Comment by jgomer2001** [comment]
think this can  be closed @maduvena ?

**Comment by MohitMaliFtechiz** [comment]
hi @yurem , message is still not user friendly on 4.2.2. , current message is "unexpected error has occurred at null "

**Comment by MohitMaliFtechiz** [comment]
this issue is fixed
